#%RAML 0.8
title: Jobvite Background Check RAML
version: 0.1

schemas:

- order-status-json-schema: !include outboundRequestSchema.jsd



/jobvite:

 /statusupdate:
  displayName: Verocity Status Update
  post:
   description: Verocity Status Update outbound endpoint
   body:
    application/json:
     schema: order-status-json-schema
   responses:
     201:
       body:
         application/json:  